# Generated by Django 3.0 on 2019-12-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='boby',
            new_name='body',
        ),
    ]
